### ISSUE TITLE
Unable to convert string concatenation in JSP EL expression

### ISSUE THREAD

**Issue by izogfif** [casid/jte#101]
If JSP file contains EL expression with string concatenation, JSP to JTE conversion fails. AFAIK string concatenation in JSP EL is written as `a += b`. Sample:
```
${Utils.getWrappedString(prefix += suffix)}
```
Error stacktrace:
```
Exception in thread "main" java.lang.UnsupportedOperationException: Unknown AST node class org.apache.el.parser.AstConcatenation. Expression was '${Utils.getWrappedString(prefix += suffix)}'
	at gg.jte.convert.jsp.converter.JspExpressionConverter.process(JspExpressionConverter.java:85)
	at gg.jte.convert.jsp.converter.JspExpressionConverter.access$3300(JspExpressionConverter.java:10)
	at gg.jte.convert.jsp.converter.JspExpressionConverter$AstMethodParametersVisitor.visit(JspExpressionConverter.java:101)
	at gg.jte.convert.jsp.converter.JspExpressionConverter.process(JspExpressionConverter.java:83)
	at gg.jte.convert.jsp.converter.JspExpressionConverter.access$3300(JspExpressionConverter.java:10)
	at gg.jte.convert.jsp.converter.JspExpressionConverter$AstFunctionVisitor.visit(JspExpressionConverter.java:338)
	at gg.jte.convert.jsp.converter.JspExpressionConverter.process(JspExpressionConverter.java:83)
	at gg.jte.convert.jsp.converter.JspExpressionConverter.<init>(JspExpressionConverter.java:72)
	at gg.jte.convert.jsp.converter.JspExpressionConverter.convertAttributeValue(JspExpressionConverter.java:15)
	at org.apache.jasper.compiler.JtpConverter.visit(JtpConverter.java:148)
	at org.apache.jasper.compiler.Node$ELExpression.accept(Node.java:958)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389)
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441)
	at org.apache.jasper.compiler.JtpConverter.visit(JtpConverter.java:162)
	at org.apache.jasper.compiler.Node$Root.accept(Node.java:470)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389)
	at org.apache.jasper.compiler.JtpConverter.convert(JtpConverter.java:79)
	at gg.jte.convert.jsp.JspToJteConverter.convertTag(JspToJteConverter.java:110)
	at gg.jte.convert.jsp.JspToJteConverter.convertTag(JspToJteConverter.java:52)
	at gg.jte.convert.jsp.JspToJteConverter.convertFromIntelliJPlugin(JspToJteConverter.java:37)
	at JspConverter.main(PortalJspConverter.java:23)
```

**Comment by casid** [comment]
I think visitors for the `+=` and also `-=`, `/=`, `*=` operators are missing here:
https://github.com/casid/jte/blob/d90909a799c28d7988e4534a47d5ff1d62ec311b/jte-jsp-converter/src/main/java/gg/jte/convert/jsp/converter/JspExpressionConverter.java#L55

I'll have a look at it this weekend.

**Comment by casid** [comment]
Damn, JSP always surprises me! You're right, that AstNode is for string concatenation and has nothing to do with the `+=` operator. Luckily this means `-=`, `/=`, `*=` is invalid in JSP EL expressions.

Would you like to have a look at my commit? Just to be sure that this is the expected conversion result:

```
${x += y}
```

gets converted to:
```
${x + y}
```

**Comment by izogfif** [comment]
Now it works. Thanks.

**Comment by casid** [comment]
Thanks for the confirmation!
