### ISSUE TITLE
JSP to JTE conversion error: Unknown AST node class org.apache.el.parser.AstListData

### ISSUE THREAD

**Issue by izogfif** [casid/jte#102]
I'm getting this error when converting this EL expression:
```
<c:if test="${[CustomEnumType.VAL_A, CustomEnumType.VAL_B, CustomEnumType.VAL_C].contains(givenValue)}">
  output some text
</c:if>
```
I think this should be converted into (Java 9+, since `java.util.Set.of` was introduced only in Java 9):
```
@if(Set.of(CustomEnumType.VAL_A, CustomEnumType.VAL_B, CustomEnumType.VAL_C).contains(givenValue))
  output some text
@endif
```
Stack trace:
```
Exception in thread "main" java.lang.UnsupportedOperationException: Unknown AST node class org.apache.el.parser.AstListData. Expression was '${[CustomEnumType.VAL_A, CustomEnumType.VAL_B, CustomEnumType.VAL_C].contains(givenValue)}'
	at gg.jte.convert.jsp.converter.JspExpressionConverter.process(JspExpressionConverter.java:86)
	at gg.jte.convert.jsp.converter.JspExpressionConverter.access$3400(JspExpressionConverter.java:10)
	at gg.jte.convert.jsp.converter.JspExpressionConverter$AstValueVisitor.visit(JspExpressionConverter.java:197)
	at gg.jte.convert.jsp.converter.JspExpressionConverter.process(JspExpressionConverter.java:84)
	at gg.jte.convert.jsp.converter.JspExpressionConverter.<init>(JspExpressionConverter.java:73)
	at gg.jte.convert.jsp.converter.JspExpressionConverter.convertAttributeValue(JspExpressionConverter.java:15)
	at gg.jte.convert.jsp.converter.JspWhenConverter.convert(JspWhenConverter.java:26)
	at org.apache.jasper.compiler.JtpConverter.visit(JtpConverter.java:216)
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389)
	at org.apache.jasper.compiler.JtpCustomTag.visitBody(JtpCustomTag.java:27)
	at org.apache.jasper.compiler.JtpConverter.lambda$visit$0(JtpConverter.java:216)
	at gg.jte.convert.jsp.converter.JspChooseConverter.convert(JspChooseConverter.java:15)
	at org.apache.jasper.compiler.JtpConverter.visit(JtpConverter.java:216)
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389)
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441)
	at org.apache.jasper.compiler.JtpConverter.visit(JtpConverter.java:162)
	at org.apache.jasper.compiler.Node$Root.accept(Node.java:470)
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389)
	at org.apache.jasper.compiler.JtpConverter.convert(JtpConverter.java:79)
	at gg.jte.convert.jsp.JspToJteConverter.convertTag(JspToJteConverter.java:110)
	at gg.jte.convert.jsp.JspToJteConverter.convertTag(JspToJteConverter.java:52)
	at gg.jte.convert.jsp.JspToJteConverter.convertFromIntelliJPlugin(JspToJteConverter.java:37)
	at MyJspConverter.main(MyJspConverter.java:23)
```

**Comment by casid** [comment]
*Shudder* :-D

`Set.of` has some surprises, like throwing NPE when null is passed as an element or if you call `contains(null)` on it. I looked into `AstListData` and it does this to populate the list:

```java
@Override
public Object getValue(EvaluationContext ctx) throws ELException {
    List<Object> result = new ArrayList<>();

    if (children != null) {
        for (Node child : children) {
            result.add(child.getValue(ctx));
        }
    }

    return result;
}
```

`java.util.Arrays.asList` should resemble this behavior close enough. I just pushed a commit with the adjustment.

The converter does not generate perfect output. At least the jte code makes it obvious that a List is allocated whenever this template is rendered. I think it might be a good idea to extract your example into an `EnumSet` constant and use that in the template.
