### ISSUE TITLE
JDK17 cannot access class com.sun.tools.javac.api.JavacTrees (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x77468bd9

### ISSUE THREAD

**Issue by qmdx** [casid/jte#175]
JDK17 cannot access class com.sun.tools.javac.api.JavacTrees (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x77468bd9

at gg.jte.compiler.java.JavaClassCompiler.runCompiler(JavaClassCompiler.java:46)
	at gg.jte.compiler.java.JavaClassCompiler.compile(JavaClassCompiler.java:37)
	at gg.jte.compiler.TemplateCompiler.precompileClasses(TemplateCompiler.java:163)
	at gg.jte.compiler.TemplateCompiler.precompile(TemplateCompiler.java:143)
	at gg.jte.compiler.TemplateCompiler.load(TemplateCompiler.java:45)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at gg.jte.TemplateEngine.resolveTemplate(TemplateEngine.java:347)
	at gg.jte.TemplateEngine.render(TemplateEngine.java:229)

**Comment by casid** [comment]
Hi @qmdx, thanks for reporting.

Do you have a sample project or steps how to reproduce this issue?

The build pipeline for jte runs without problems on JDK 17, so I'm a bit lost how to proceed.

**Comment by qmdx** [comment]
Sorry, other dependencies on my side cause  `JTE ` exceptions
