### ISSUE TITLE
Param without name leads to unclear error

### ISSUE THREAD

**Issue by JavalinPony** [casid/jte#24]
`@param foo.Page` without a name leads to

```
java.lang.StringIndexOutOfBoundsException: begin -1, end 8, length 8
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at gg.jte.internal.ParamInfo.<init>(ParamInfo.java:64)
	at gg.jte.internal.TemplateParser.lambda$doParse$1(TemplateParser.java:111)
	at gg.jte.internal.TemplateParser.extract(TemplateParser.java:731)
	at gg.jte.internal.TemplateParser.doParse(TemplateParser.java:111)
	at gg.jte.internal.TemplateParser.parse(TemplateParser.java:79)
	at gg.jte.internal.TemplateParser.parse(TemplateParser.java:74)
	at gg.jte.internal.TemplateCompiler.generateTemplate(TemplateCompiler.java:116)
	at gg.jte.internal.TemplateCompiler.generate(TemplateCompiler.java:87)
	at gg.jte.internal.TemplateCompiler.precompile(TemplateCompiler.java:69)
	at gg.jte.internal.TemplateCompiler.load(TemplateCompiler.java:40)
	at gg.jte.TemplateEngine.resolveTemplate(TemplateEngine.java:267)
	at gg.jte.TemplateEngine.render(TemplateEngine.java:151)
	at io.javalin.plugin.rendering.template.JavalinJte.render(JavalinJte.kt:33)
	at io.javalin.plugin.rendering.JavalinRenderer.renderBasedOnExtension(JavalinRenderer.kt:34)
	at io.javalin.http.Context.render(Context.kt:480)
	at io.javalin.http.Context.render$default(Context.kt:479)
	at io.javalin.http.Context.render(Context.kt)
	at foo.Main.lambda$main$1(Main.java:16)
	...
```
Using Java 11.
Javalin version: 3.11.0
jte version: 1.3.0

A more descriptive error message would be helpful.

**Comment by casid** [comment]
Hi @JavalinPony, thanks for reporting!

I've written a fix for it what do you think about the error message?
https://github.com/casid/jte/commit/a164a459bb64612ec4c7d6ca2bdb8d9954c0e4d8

For your example it would be:
`Failed to compile test/template.jte, error at line 1: Missing parameter name: '@param foo.Page'`

**Comment by casid** [comment]
Awesome, thanks!
