### ISSUE TITLE
[Feature request] Ktor support

### ISSUE THREAD

**Issue by dector** [casid/jte#35]
Hi! I'm trying to use JTE with Ktor but only only simple examples work. When I'm trying to use custom models - classloader mess happens :)

Will prepare minimal sample later. Any ideas to overcome this issue with dirty fix on my side now?

```
Caused by: java.lang.ClassCastException: class app.Model cannot be cast to class app.Model (app.Model is in unnamed module of loader io.ktor.server.engine.OverridingClassLoader$ChildURLClassLoader @4d0d9fe7; app.Model is in unnamed module of loader 'app')
	at gg.jte.generated.JtedashboardGenerated.render(JtedashboardGenerated.java:9)
	at gg.jte.generated.JtedashboardGenerated.renderMap(JtedashboardGenerated.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at gg.jte.internal.Template.renderMap(Template.java:49)
	at gg.jte.TemplateEngine.render(TemplateEngine.java:153)
```

**Comment by casid** [comment]
Looks like Ktor uses a different classloader than the application class loader.

I think it could work if we allow to configure the parent class loader jte uses in `gg.jte.internal.TemplateLoader`.

```java
    protected ClassLoader createClassLoader() {
        try {
            return new URLClassLoader(new URL[]{classDirectory.toUri().toURL()});
        } catch (MalformedURLException e) {
            throw new TemplateException("Failed to create class loader for " + classDirectory, e);
        }
    }
```

**Comment by casid** [comment]
@dector I added a factory method to create a template engine with a parent class loader.

Would you like to give it a try if this helps to get it running with Ktor?

You'd need to clone this repository, run `mvn install` on jte-parent and use version `1.5.0-SNAPSHOT` as dependency.

**Comment by dector** [comment]
Awesome, thanks! I will try providing class loader today and tell you what are the results.
Really appreciated for the help!

**Comment by dector** [comment]
@casid I can confirm that providing child (not app) classloader to `TemplateEngine` factory method works fine.

You can close this issue for now - I'll create new one with PR when I'll be able to bundle this functionality as a Ktor Feature.

**Comment by kelunik** [comment]
@dector Cool, thanks for reporting back! :smile:

**Comment by dector** [comment]
JIC: Using [Jitpack version](https://jitpack.io/#casid/jte/733e354b5e) for now.

**Comment by casid** [comment]
@dector that's pretty cool! Thanks for testing and reporting back so quickly.

**Comment by casid** [comment]
@dector release 1.5.0 is out and available on maven central. It contains this feature :-)

**Comment by dector** [comment]
@casid Thank you, will update! :)
