### ISSUE TITLE
PluginException: ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon.

### ISSUE THREAD

**Issue by mfietz** [casid/jte#367]
IntelliJ warns me about an error in the plugin:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.jusecase.jte.intellij.language.convert.JteConvertFromJspAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.jusecase.jte-intellij]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by casid** [comment]
Thanks for reporting, I'll move this over to the jte-intellij repository.
