### ISSUE TITLE
Template names with dots lead to failure

### ISSUE THREAD

**Issue by Virtlink** [casid/jte#369]
I have a template resource with name `.github/workflows/build.yaml`. When precompiling this generates a class definition with the name `gg.jte.generated.ondemand..github.workflows.JtebuildyamlGenerated` (note the double dot in the name). JTE then later tries to find the class named `gg.jte.generated.ondemand.github.workflows.JtebuildyamlGenerated` at `jte-classes/gg/jte/generated/ondemand/github/workflows/JtebuildyamlGenerated.kt` (note that the package name now doesn't contain the extra dot).

This causes some errors when compiling the generated Kotlin file, but the errors can't be displayed because of a NullPointerException.

```
Exception in thread "main" java.lang.NullPointerException: Cannot read field "lineInfo" because "templateInfo" is null
	at gg.jte.compiler.kotlin.KotlinClassCompiler$SimpleKotlinCompilerMessageCollector.getErrorMessage(KotlinClassCompiler.java:121)
	at gg.jte.compiler.kotlin.KotlinClassCompiler.compile(KotlinClassCompiler.java:49)
	at gg.jte.compiler.TemplateCompiler.precompileClasses(TemplateCompiler.java:114)
	at gg.jte.compiler.TemplateCompiler.precompile(TemplateCompiler.java:94)
	at gg.jte.compiler.TemplateCompiler.load(TemplateCompiler.java:50)
	at gg.jte.TemplateEngine.lambda$resolveTemplateOnDemand$0(TemplateEngine.java:354)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at gg.jte.TemplateEngine.resolveTemplateOnDemand(TemplateEngine.java:347)
	at gg.jte.TemplateEngine.resolveTemplate(TemplateEngine.java:337)
	at gg.jte.TemplateEngine.render(TemplateEngine.java:210)
```

JTE and JTE Kotlin version 3.1.12.

---

I think the template names must be normalized to valid Java (package) names, removing such things as illegal characters and dots, before being processed further by JTE.

**Comment by casid** [comment]
Dots in package names are not supported. Same for jte packages. Would it be possible for you to set the root directory of the template engine to e.g. `.github/workflows/`?
