### ISSUE TITLE
Type Mismatch for Parameter with identical types in Spring Boot

### ISSUE THREAD

**Issue by zachtib** [casid/jte#70]
I'm toying around with adding jte(-kotlin) into a Spring Boot project.

To accomplish this, I have a custom ViewResolver and View class that use JTE to render the result html. The `@param` type is stored on the Spring Model and retrieved before rendering the view.

When I try to actually render a template, I'm getting a very bizarre error.

The full stack trace I'm getting is:

```
There was an unexpected error (type=Internal Server Error, status=500).
Failed to render hello.kte, type mismatch for parameter: Expected com.example.jtedemo.HelloModel, got com.example.jtedemo.HelloModel
gg.jte.TemplateException: Failed to render hello.kte, type mismatch for parameter: Expected com.example.jtedemo.HelloModel, got com.example.jtedemo.HelloModel
	at gg.jte.runtime.Template.render(Template.java:43)
	at gg.jte.TemplateEngine.render(TemplateEngine.java:213)
	at com.example.jtedemo.jte.JteView.render(JteView.kt:14)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1393)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1138)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1077)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at gg.jte.runtime.Template.render(Template.java:36)
	... 44 more
```

And the source for this example is at https://github.com/zachtib/SpringBootDemoWithJTE

I'm new to both JTE and Spring, so there's every chance I'm just doing something very wrong, but I'd like to get these two tools playing nice with each other.

**Comment by casid** [comment]
@zachtib this looks like a class loading error.

I think jte uses the current thread's context class loader, when no class loader is specified.

Can you try to check what classloader spring uses? If you temporarily print this in your Spring controller, just before invoking the template engine?
`System.out.println(Thread.currentThread().getContextClassLoader());`
`System.out.println(getClass().getClassLoader());`

There's a factory method in `TemplateEngine` that accepts a class loader as argument. My guess would be that you need to pass the correct one from Spring there, to fix this issue.

**Comment by zachtib** [comment]
That did it! I had to make a follow up tweak to flush the output stream on my TemplateOutput, and now I have it correctly rendering and displaying pages in Spring Boot! I've pushed the fix to that example repo in the original issue.

Thanks!

**Comment by casid** [comment]
Awesome! Glad it worked out :-)
